<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_addToCart2</name>
   <tag></tag>
   <elementGuidId>933df8f7-202d-40ad-b7b2-55ce7d7e3d1f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[16]/div[1]/div[2]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn') and equals(@title,'Add to cart') and equals(@type,'button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(16) .btn</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li:nth-child(16) &gt; .products__item-wrapper &gt; .products__offer-row &gt; .products__to-cart &gt; .btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-to-cart products__to-cart-btn</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
