<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_buy</name>
   <tag></tag>
   <elementGuidId>75c20530-95a5-4579-bbb2-8f624448aebc</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]/*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'svg-inline--fa fa-cart-plus fa-w-18 ') and equals(@role,'img')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn-anim &gt; [class="svg-inline--fa\ fa-cart-plus\ fa-w-18\ "]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button[title=\"Buy\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-cart-plus fa-w-18 </value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
