<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_buy2</name>
   <tag></tag>
   <elementGuidId>3e916f9d-7f6c-4a21-bb39-518612a0b100</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-action btn-anim btn-lg') and equals(@title,'Buy') and equals(@type,'button') and equals(@text,' Buy')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="btn\ btn-action\ btn-anim\ btn-lg"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button[title=\"Buy\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action btn-anim btn-lg</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buy</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
