<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_addToCart</name>
   <tag></tag>
   <elementGuidId>a621c341-2c06-4273-8ad1-a7c89208d25b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[2]/div[1]/div[2]/div[2]/button[1]/*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'svg-inline--fa fa-cart-plus fa-w-18 ') and equals(@role,'img')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) [class="svg-inline--fa\ fa-cart-plus\ fa-w-18\ "]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li:nth-child(2) &gt; .products__item-wrapper &gt; .products__offer-row &gt; .products__to-cart &gt; .btn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-cart-plus fa-w-18 </value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
