<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_kCellphoneShopContainer</name>
   <tag></tag>
   <elementGuidId>8bee9ce1-4d26-4628-9e0c-ec24b119838c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'container-xxl mars-logo-row__container') and equals(@text,'K Cellphone Shop
         Welcome to our shop. We are working for you!
         0')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="container-xxl\ mars-logo-row__container"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-xxl mars-logo-row__container</value>
      <webElementGuid>8299dafb-2bca-4e20-98e5-04026ac0cb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K Cellphone Shop
      Welcome to our shop. We are working for you!
      0</value>
      <webElementGuid>8299dafb-2bca-4e20-98e5-04026ac0cb8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
