<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_product</name>
   <tag></tag>
   <elementGuidId>f9bd98e1-160d-4c20-a2e0-5ef560487d81</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/ul[1]/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'products__item in-stock products__item_4-in-row') and equals(@text,'iPhone 15 Silicone Case with Magsafe
         $ 39.00')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.products &gt; li:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.products &gt; li:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>products__item in-stock products__item_4-in-row</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone 15 Silicone Case with Magsafe
      $ 39.00</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
