<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_prevButton</name>
   <tag></tag>
   <elementGuidId>a7b52abd-2b77-484f-beb9-dcebd22548ff</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'swiper-slider__prev swiper-button-disabled') and equals(@href,'#')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="swiper-slider__prev\ swiper-button-disabled"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.swiper-slider__prev</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swiper-slider__prev swiper-button-disabled</value>
      <webElementGuid>8299dafb-2bca-4e20-98e5-04026ac0cb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8299dafb-2bca-4e20-98e5-04026ac0cb8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
