<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_accessories</name>
   <tag></tag>
   <elementGuidId>bf9beaf3-400e-41b7-abec-dd63521d12c0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'horizontal-menu__element is-link is-root children-visible') and equals(@href,'/category/accessories') and equals(@text,'Accessories')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="horizontal-menu__element\ is-link\ is-root\ children-visible"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:has-text=/^Accessories$/ &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>horizontal-menu__element is-link is-root children-visible</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category/accessories</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accessories</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
</WebElementEntity>
