<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_colorOption</name>
   <tag></tag>
   <elementGuidId>a46fc626-f2fb-444b-b6dc-d9fa9db9c9b5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[4]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-outline-secondary') and equals(@text,'Black')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>${label_colorOption_css_value_1}</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label &gt;&gt; internal:text=\"${label_colorOption_LabelInternalText_1}\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-secondary</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Black</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
