<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_addToCart</name>
   <tag></tag>
   <elementGuidId>04d9ba7f-200f-41e1-9a7e-f25796a81189</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[2]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn') and equals(@title,'Add to cart') and equals(@type,'button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) .btn</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt;&gt; internal:has-text=/^Apple iPhone 15 Pro Silicone Case with MagSafe\\$ 25\\.00$/ &gt;&gt; button[title=\"Add to cart\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-to-cart products__to-cart-btn</value>
      <webElementGuid>796419dc-f941-406c-b6a4-e7ddc6682f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>796419dc-f941-406c-b6a4-e7ddc6682f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>796419dc-f941-406c-b6a4-e7ddc6682f26</webElementGuid>
   </webElementProperties>
</WebElementEntity>
