<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_placeOrder</name>
   <tag></tag>
   <elementGuidId>4c228a2b-ee12-422d-a9d3-ddcc29ccfe99</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-action btn-anim') and equals(@href,'/cart') and equals(@text,' Place an order')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn-anim</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text=\"Place an order\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action btn-anim</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Place an order</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
</WebElementEntity>
