<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_proceedToCheckout</name>
   <tag></tag>
   <elementGuidId>672c5424-d4d8-4821-ba52-fd16ec22a9f3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'btn btn-action btn-lg btn-anim') and equals(@text,'Proceed to checkout ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="btn\ btn-action\ btn-lg\ btn-anim"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button &gt;&gt; internal:text=\"Proceed to checkout\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-action btn-lg btn-anim</value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to checkout </value>
      <webElementGuid>f1a23022-01f4-4b1b-9732-a0b179a15059</webElementGuid>
   </webElementProperties>
</WebElementEntity>
