<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_apple</name>
   <tag></tag>
   <elementGuidId>78cc7d10-8347-4f4a-a51a-ce09c6c620b6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@class,'horizontal-menu__element is-link is-child') and equals(@href,'/category/accessories-apple') and equals(@text,'Apple')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) &gt; [class="horizontal-menu__element\ is-link\ is-child"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:has-text=/^Apple$/ &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>horizontal-menu__element is-link is-child</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category/accessories-apple</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple</value>
      <webElementGuid>38d95ea6-a8dc-4d5b-8609-869eb57d19f2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
