<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_samsung25WpowerAdapter</name>
   <tag></tag>
   <elementGuidId>234ae348-2ba1-46ef-8b70-9b92eba7b6a4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@href,'/product/samsung-25w-power-adapter-without-cable') and equals(@text,'Samsung 25W Power Adapter (Without Cable)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="cart-item__title"] a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text=\"Samsung 25W Power Adapter (Without Cable)\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/samsung-25w-power-adapter-without-cable</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung 25W Power Adapter (Without Cable)</value>
      <webElementGuid>48dbb3bf-a3ff-422e-840c-2a44d624db77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
